name: 'athens_dbt'
version: '1.0.0'
config-version: 2
profile: 'athens_dbt'
model-paths: ["athens_dbt/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:      
  - "target"
  - "dbt_packages"
models:
  athens_dbt:
    data_clean:
    veh_type:
    veh_speed:
    stopped_veh:
       +materialized: table
